markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: HJ Meulekamp
url: http://serversidedeveloper.com
description: Testing another blog engine
twitter: hjmeulekamp
